version: '2'
services:
  torus:
    network_mode: host
    image: quay.io/coreos/torus
    volumes:
      - ./data1:/data
    environment:
      - STORAGE_SIZE=20GiB
      - LISTEN_HOST=0.0.0.0
      - LISTEN_HTTP_PORT=4321
      - PEER_ADDRESS=http://192.168.59.103:40000
      - ETCD_HOST=192.168.59.103
      - ETCD_PORT=2379
      - DEBUG=1
      - DEBUG_INIT=1
    ports:
      - "40000:40000"
      - "4321:4321"
    depends_on:
      - "etcd"

  etcd:
    network_mode: host
    image: quay.io/coreos/etcd
    command: >
      -listen-client-urls http://0.0.0.0:2379
      -advertise-client-urls http://192.168.59.103:2379
      -initial-cluster-state new
    volumes:
      - ./data1:/data
    ports:
      - "2379:2379"
